version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "5500:80"
    volumes:
      - .:/var/www/html


  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1
